/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as SearchVercelRouteImport } from './routes/search/vercel'
import { Route as SearchTanstackRouteImport } from './routes/search/tanstack'
import { Route as SearchCloudflareRouteImport } from './routes/search/cloudflare'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChangelogSplatRouteImport } from './routes/changelog/$'
import { Route as ApiDocsSearchRouteImport } from './routes/api/docs/search'
import { Route as ApiDocsAskRouteImport } from './routes/api/docs/ask'
import { Route as ApiDocsAskVercelRouteImport } from './routes/api/docs/ask/vercel'
import { Route as ApiDocsAskTanstackRouteImport } from './routes/api/docs/ask/tanstack'
import { Route as ApiDocsAskCloudflareRouteImport } from './routes/api/docs/ask/cloudflare'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const SearchVercelRoute = SearchVercelRouteImport.update({
  id: '/vercel',
  path: '/vercel',
  getParentRoute: () => SearchRoute,
} as any)
const SearchTanstackRoute = SearchTanstackRouteImport.update({
  id: '/tanstack',
  path: '/tanstack',
  getParentRoute: () => SearchRoute,
} as any)
const SearchCloudflareRoute = SearchCloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => SearchRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ChangelogSplatRoute = ChangelogSplatRouteImport.update({
  id: '/changelog/$',
  path: '/changelog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSearchRoute = ApiDocsSearchRouteImport.update({
  id: '/api/docs/search',
  path: '/api/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsAskRoute = ApiDocsAskRouteImport.update({
  id: '/api/docs/ask',
  path: '/api/docs/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsAskVercelRoute = ApiDocsAskVercelRouteImport.update({
  id: '/vercel',
  path: '/vercel',
  getParentRoute: () => ApiDocsAskRoute,
} as any)
const ApiDocsAskTanstackRoute = ApiDocsAskTanstackRouteImport.update({
  id: '/tanstack',
  path: '/tanstack',
  getParentRoute: () => ApiDocsAskRoute,
} as any)
const ApiDocsAskCloudflareRoute = ApiDocsAskCloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => ApiDocsAskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRouteWithChildren
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/search/cloudflare': typeof SearchCloudflareRoute
  '/search/tanstack': typeof SearchTanstackRoute
  '/search/vercel': typeof SearchVercelRoute
  '/docs/': typeof DocsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRouteWithChildren
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/api/docs/ask/cloudflare': typeof ApiDocsAskCloudflareRoute
  '/api/docs/ask/tanstack': typeof ApiDocsAskTanstackRoute
  '/api/docs/ask/vercel': typeof ApiDocsAskVercelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/search/cloudflare': typeof SearchCloudflareRoute
  '/search/tanstack': typeof SearchTanstackRoute
  '/search/vercel': typeof SearchVercelRoute
  '/docs': typeof DocsIndexRoute
  '/search': typeof SearchIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRouteWithChildren
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/api/docs/ask/cloudflare': typeof ApiDocsAskCloudflareRoute
  '/api/docs/ask/tanstack': typeof ApiDocsAskTanstackRoute
  '/api/docs/ask/vercel': typeof ApiDocsAskVercelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRouteWithChildren
  '/changelog/$': typeof ChangelogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/search/cloudflare': typeof SearchCloudflareRoute
  '/search/tanstack': typeof SearchTanstackRoute
  '/search/vercel': typeof SearchVercelRoute
  '/docs/': typeof DocsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRouteWithChildren
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/api/docs/ask/cloudflare': typeof ApiDocsAskCloudflareRoute
  '/api/docs/ask/tanstack': typeof ApiDocsAskTanstackRoute
  '/api/docs/ask/vercel': typeof ApiDocsAskVercelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/changelog/$'
    | '/docs/$'
    | '/search/cloudflare'
    | '/search/tanstack'
    | '/search/vercel'
    | '/docs/'
    | '/search/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/api/docs/ask/cloudflare'
    | '/api/docs/ask/tanstack'
    | '/api/docs/ask/vercel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/changelog/$'
    | '/docs/$'
    | '/search/cloudflare'
    | '/search/tanstack'
    | '/search/vercel'
    | '/docs'
    | '/search'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/api/docs/ask/cloudflare'
    | '/api/docs/ask/tanstack'
    | '/api/docs/ask/vercel'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/changelog/$'
    | '/docs/$'
    | '/search/cloudflare'
    | '/search/tanstack'
    | '/search/vercel'
    | '/docs/'
    | '/search/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/api/docs/ask/cloudflare'
    | '/api/docs/ask/tanstack'
    | '/api/docs/ask/vercel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  SearchRoute: typeof SearchRouteWithChildren
  ChangelogSplatRoute: typeof ChangelogSplatRoute
  ApiDocsAskRoute: typeof ApiDocsAskRouteWithChildren
  ApiDocsSearchRoute: typeof ApiDocsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/search/vercel': {
      id: '/search/vercel'
      path: '/vercel'
      fullPath: '/search/vercel'
      preLoaderRoute: typeof SearchVercelRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/tanstack': {
      id: '/search/tanstack'
      path: '/tanstack'
      fullPath: '/search/tanstack'
      preLoaderRoute: typeof SearchTanstackRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/cloudflare': {
      id: '/search/cloudflare'
      path: '/cloudflare'
      fullPath: '/search/cloudflare'
      preLoaderRoute: typeof SearchCloudflareRouteImport
      parentRoute: typeof SearchRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/changelog/$': {
      id: '/changelog/$'
      path: '/changelog/$'
      fullPath: '/changelog/$'
      preLoaderRoute: typeof ChangelogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/search': {
      id: '/api/docs/search'
      path: '/api/docs/search'
      fullPath: '/api/docs/search'
      preLoaderRoute: typeof ApiDocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/ask': {
      id: '/api/docs/ask'
      path: '/api/docs/ask'
      fullPath: '/api/docs/ask'
      preLoaderRoute: typeof ApiDocsAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/ask/vercel': {
      id: '/api/docs/ask/vercel'
      path: '/vercel'
      fullPath: '/api/docs/ask/vercel'
      preLoaderRoute: typeof ApiDocsAskVercelRouteImport
      parentRoute: typeof ApiDocsAskRoute
    }
    '/api/docs/ask/tanstack': {
      id: '/api/docs/ask/tanstack'
      path: '/tanstack'
      fullPath: '/api/docs/ask/tanstack'
      preLoaderRoute: typeof ApiDocsAskTanstackRouteImport
      parentRoute: typeof ApiDocsAskRoute
    }
    '/api/docs/ask/cloudflare': {
      id: '/api/docs/ask/cloudflare'
      path: '/cloudflare'
      fullPath: '/api/docs/ask/cloudflare'
      preLoaderRoute: typeof ApiDocsAskCloudflareRouteImport
      parentRoute: typeof ApiDocsAskRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface SearchRouteChildren {
  SearchCloudflareRoute: typeof SearchCloudflareRoute
  SearchTanstackRoute: typeof SearchTanstackRoute
  SearchVercelRoute: typeof SearchVercelRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchCloudflareRoute: SearchCloudflareRoute,
  SearchTanstackRoute: SearchTanstackRoute,
  SearchVercelRoute: SearchVercelRoute,
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface ApiDocsAskRouteChildren {
  ApiDocsAskCloudflareRoute: typeof ApiDocsAskCloudflareRoute
  ApiDocsAskTanstackRoute: typeof ApiDocsAskTanstackRoute
  ApiDocsAskVercelRoute: typeof ApiDocsAskVercelRoute
}

const ApiDocsAskRouteChildren: ApiDocsAskRouteChildren = {
  ApiDocsAskCloudflareRoute: ApiDocsAskCloudflareRoute,
  ApiDocsAskTanstackRoute: ApiDocsAskTanstackRoute,
  ApiDocsAskVercelRoute: ApiDocsAskVercelRoute,
}

const ApiDocsAskRouteWithChildren = ApiDocsAskRoute._addFileChildren(
  ApiDocsAskRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  SearchRoute: SearchRouteWithChildren,
  ChangelogSplatRoute: ChangelogSplatRoute,
  ApiDocsAskRoute: ApiDocsAskRouteWithChildren,
  ApiDocsSearchRoute: ApiDocsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
