// Build-time exports.

export {
  type DocsFeedConfig,
  type FeedEntry,
  type FeedFormat,
  type GenerateFeedArtifactsConfig,
  type GenerateFeedArtifactsResult,
  generateFeedArtifacts,
  type RenderFeedConfig,
  renderAtomFeed,
  renderRssFeed,
} from "../feed";
export {
  type AlternateLocaleLink,
  type DocsI18nConfig,
  type DocsI18nManifest,
  type DocsLocale,
  getAlternateLocaleLinks,
  type LocaleCode,
  listDocsLocales,
  normalizeDocsI18nConfig,
  resolveDocsLocale,
  stripLocaleFromDocsPath,
  toLocalizedDocsUrlPath,
  toLocalizedMarkdownUrlPath,
} from "../i18n";
export {
  type AgentPageInput,
  type AgentReadabilityConfig,
  type AgentReadabilityResult,
  type AgentsMdConfig,
  type AgentsMdResult,
  type CuratedLink,
  type DocsAgentsConfig,
  type DocsCollection,
  type DocsConfig,
  type DocsFrontmatterSchema,
  type DocsGitConfig,
  type DocsGroup,
  type DocsLlmsConfig,
  type DocsNavEntry,
  type DocsNavIncludeEntry,
  type DocsNavNode,
  type DocsNavPageEntry,
  type DocsNavSortKey,
  type DocsPathMount,
  type DocsSkillSpec,
  type DocsTableOfContentsPage,
  defineCollection,
  defineDocsConfig,
  defineFrameworkNavigation,
  extractDocsTableOfContents,
  type FrameworkNavigationConfig,
  type FrameworkNavigationTemplate,
  type FrameworkNavigationVariant,
  type GenerateAgentArtifactsConfig,
  type GenerateAgentArtifactsResult,
  generateAgentArtifacts,
  generateAgentReadabilityArtifacts,
  generateAgentsMd,
  generateLLMFullContextFiles,
  generateLlmsTxt,
  type LLMFullContextConfig,
  type LlmsBlock,
  type LlmsProductInfo,
  type LlmsTxtConfig,
  type MarkdownDoc,
  type OrganizationInfo,
  type ProductInfo,
  type ResolveDocsNavigationConfig,
  type ResolveDocsTableOfContentsConfig,
  type ResolvedAgentInputs,
  resolveAgentInputs,
  resolveDocsNavigation,
  resolveDocsTableOfContents,
  type SourceConfigInheritance,
  type SourceConfigInheritField,
  type SourceDoc,
} from "./llm";
// Runtime + shared types and helpers.
export {
  type AgentArtifactResponseConfig,
  type AgentDiscoveryLinksConfig,
  type AgentReadabilityManifest,
  type AgentReadabilityPage,
  type AgentRequestHeaders,
  acceptsMarkdownHeader,
  type CreateAgentMarkdownResponseConfig,
  type CreateApiCatalogResponseConfig,
  type CreateDocsHeadConfig,
  type CreateRobotsTxtResponseConfig,
  type CreateSitemapMarkdownResponseConfig,
  createAgentDiscoveryHeaders,
  createAgentDiscoveryLinkHeader,
  createAgentMarkdownResponse,
  createApiCatalogResponse,
  createDocsHead,
  createMarkdownResponseHeaders,
  createRobotsTxtResponse,
  createSitemapMarkdownResponse,
  createSitemapXmlResponse,
  type DocsHead,
  type DocsHeadEntry,
  type DocsNavigation,
  type DocsNavigationGroup,
  type DocsNavigationPage,
  type DocsTableOfContentsItem,
  type DocsTableOfContentsOptions,
  type EnrichMarkdownFrontmatterConfig,
  enrichMarkdownFrontmatter,
  isAgentReadabilityArtifactPath,
  isAgentUserAgent,
  type JsonLdValue,
  type MarkdownMirrorTarget,
  type MarkdownResponseHeadersConfig,
  normalizeAgentReadabilityManifest,
  type RenderApiCatalogConfig,
  type RenderMissingMarkdownConfig,
  type RenderRobotsTxtConfig,
  type RenderSiteJsonLdOptions,
  type RenderSitemapMarkdownConfig,
  renderApiCatalog,
  renderJsonLd,
  renderJsonLdScript,
  renderMissingMarkdown,
  renderRobotsTxt,
  renderSiteJsonLd,
  renderSitemapMarkdown,
  renderSitemapXml,
  resolveMarkdownMirrorTarget,
  slugifyDocsHeading,
  validateJsonLd,
} from "./readability";
export {
  type GenerateSkillArtifactsConfig,
  type GenerateSkillArtifactsResult,
  generateSkillArtifacts,
} from "./skills";
