// Build-time exports.

export {
  type AlternateLocaleLink,
  type DocsI18nConfig,
  type DocsI18nManifest,
  type DocsLocale,
  getAlternateLocaleLinks,
  type LocaleCode,
  listDocsLocales,
  normalizeDocsI18nConfig,
  resolveDocsLocale,
  stripLocaleFromDocsPath,
  toLocalizedDocsUrlPath,
  toLocalizedMarkdownUrlPath,
} from "../i18n";
export {
  type AgentReadabilityConfig,
  type AgentReadabilityResult,
  type AgentsMdConfig,
  type AgentsMdResult,
  type CuratedLink,
  type DocsAgentsConfig,
  type DocsCollection,
  type DocsConfig,
  type DocsFrontmatterSchema,
  type DocsGroup,
  type DocsLlmsConfig,
  type DocsNavIncludeEntry,
  type DocsNavNode,
  type DocsNavPageEntry,
  type DocsNavSortKey,
  type DocsSkillSpec,
  type DocsTableOfContentsPage,
  defineCollection,
  defineDocsConfig,
  extractDocsTableOfContents,
  generateAgentReadabilityArtifacts,
  generateAgentsMd,
  generateLLMFullContextFiles,
  generateLlmsTxt,
  type LLMFullContextConfig,
  type LlmsBlock,
  type LlmsProductInfo,
  type LlmsTxtConfig,
  type MarkdownDoc,
  type OrganizationInfo,
  type ProductInfo,
  type ResolveDocsNavigationConfig,
  type ResolveDocsTableOfContentsConfig,
  type ResolvedAgentInputs,
  resolveAgentInputs,
  resolveDocsNavigation,
  resolveDocsTableOfContents,
  type SourceConfigInheritance,
  type SourceConfigInheritField,
  type SourceDoc,
} from "./llm";
// Runtime + shared types and helpers.
export {
  type AgentArtifactResponseConfig,
  type AgentReadabilityManifest,
  type AgentReadabilityPage,
  type AgentRequestHeaders,
  acceptsMarkdownHeader,
  type CreateAgentMarkdownResponseConfig,
  type CreateDocsHeadConfig,
  type CreateRobotsTxtResponseConfig,
  type CreateSitemapMarkdownResponseConfig,
  createAgentMarkdownResponse,
  createDocsHead,
  createMarkdownResponseHeaders,
  createRobotsTxtResponse,
  createSitemapMarkdownResponse,
  createSitemapXmlResponse,
  type DocsHead,
  type DocsHeadEntry,
  type DocsNavigation,
  type DocsNavigationGroup,
  type DocsNavigationPage,
  type DocsTableOfContentsItem,
  type DocsTableOfContentsOptions,
  type EnrichMarkdownFrontmatterConfig,
  enrichMarkdownFrontmatter,
  isAgentReadabilityArtifactPath,
  isAgentUserAgent,
  type JsonLdValue,
  type MarkdownMirrorTarget,
  type MarkdownResponseHeadersConfig,
  normalizeAgentReadabilityManifest,
  type RenderMissingMarkdownConfig,
  type RenderRobotsTxtConfig,
  type RenderSiteJsonLdOptions,
  type RenderSitemapMarkdownConfig,
  renderJsonLd,
  renderJsonLdScript,
  renderMissingMarkdown,
  renderRobotsTxt,
  renderSiteJsonLd,
  renderSitemapMarkdown,
  renderSitemapXml,
  resolveMarkdownMirrorTarget,
  slugifyDocsHeading,
  validateJsonLd,
} from "./readability";
export {
  type GenerateSkillArtifactsConfig,
  type GenerateSkillArtifactsResult,
  generateSkillArtifacts,
} from "./skills";
