import { rehypeCode } from "fumadocs-core/mdx-plugins";
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
} from "fumadocs-ui/layouts/docs/page";
import {
  createDocsJsonLd,
  normalizeAgentReadabilityManifest,
  stringifyJsonLd,
} from "leadtype/llm/readability";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { MDXRemote } from "next-mdx-remote-client/rsc";
import { mdxComponents } from "@/lib/mdx-components";
import { leadtypeSource } from "@/lib/source";
import manifestJson from "../../../public/docs/agent-readability.json";

// Agent-readability manifest generated by `docs:generate` over the c15t source.
// Drives JSON-LD here and canonical URLs in generateMetadata, so the fumadocs
// UI and the agent surface share one source of truth.
const manifest = normalizeAgentReadabilityManifest(manifestJson);

const mdxOptions = {
  // Syntax highlight code blocks. Tokens use the same shiki theme + classes
  // that fumadocs-ui's codeblock CSS is designed for.
  rehypePlugins: [rehypeCode],
};

type PageParams = Promise<{ slug?: string[] }>;

function toUrlPath(slug: string[]): string {
  return slug.length > 0 ? `/docs/${slug.join("/")}` : "/docs";
}

export default async function DocsPageRoute({
  params,
}: {
  params: PageParams;
}) {
  const { slug = [] } = await params;
  const page = await leadtypeSource.loadPage(slug);

  if (!page) {
    notFound();
  }

  const jsonLd = createDocsJsonLd({ urlPath: toUrlPath(slug), manifest });

  return (
    <DocsPage
      toc={page.toc.map((item) => ({
        title: item.title,
        url: `#${item.id}`,
        depth: item.level,
      }))}
    >
      {jsonLd ? (
        <script type="application/ld+json">{stringifyJsonLd(jsonLd)}</script>
      ) : null}
      <DocsTitle>{page.title}</DocsTitle>
      {page.description ? (
        <DocsDescription>{page.description}</DocsDescription>
      ) : null}
      <DocsBody>
        <MDXRemote
          components={mdxComponents}
          options={{ mdxOptions }}
          source={page.markdown}
        />
      </DocsBody>
    </DocsPage>
  );
}

export async function generateStaticParams() {
  const pages = await leadtypeSource.listPages();
  return pages.map((page) => ({ slug: page.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: PageParams;
}): Promise<Metadata> {
  const { slug = [] } = await params;
  const page = await leadtypeSource.loadPage(slug);
  if (!page) {
    return {};
  }
  const meta = manifest.pages.find(
    (entry) => entry.urlPath === toUrlPath(slug)
  );
  return {
    title: `${page.title} — c15t docs`,
    description: page.description,
    alternates: meta ? { canonical: meta.absoluteUrl } : undefined,
  };
}
