/** @biome-ignore lint/performance/noBarrelFile: package entry point */

export {
  BUILTIN_FLATTENER_COMPONENT_NAMES,
  type Builders,
  b,
  builtinFlattenerPlugins,
  builtinMarkdownFlattenerTransforms,
  type ComponentFlattenerSpec,
  createBlockquote,
  createHeading,
  createInlineCode,
  createJsxComponentProcessor,
  createLink,
  createListItem,
  createOrderedList,
  createParagraph,
  createStrong,
  createStrongParagraph,
  createTable,
  createTableCell,
  createTableRow,
  createText,
  createUnorderedList,
  defaultMarkdownTransforms,
  defaultRemarkPlugins,
  defineComponentFlattener,
  extractNodeText,
  extractTypeFromFile,
  type FlattenContext,
  type FlattenResult,
  getAttributeValue,
  hasName,
  type InferProps,
  type MdxNode,
  normalizeWhitespace,
  type PropKind,
  type PropsSpec,
  parseItemsArray,
  parseMarkdown,
  processContentNode,
  remarkTypeTableToMarkdown,
  typeTableToMarkdown,
} from "../markdown";
export { remarkInclude } from "./plugins/include.remark";
