/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSearchRouteImport } from './routes/docs/search'
import { Route as DocsRemarkRouteImport } from './routes/docs/remark'
import { Route as DocsMethodologyRouteImport } from './routes/docs/methodology'
import { Route as DocsLlmRouteImport } from './routes/docs/llm'
import { Route as DocsLintRouteImport } from './routes/docs/lint'
import { Route as DocsConvertRouteImport } from './routes/docs/convert'
import { Route as DocsComponentsRouteImport } from './routes/docs/components'
import { Route as DocsGuidesConnectDocsSiteRouteImport } from './routes/docs/guides/connect-docs-site'
import { Route as DocsGuidesBundlePackageDocsRouteImport } from './routes/docs/guides/bundle-package-docs'
import { Route as ApiDocsSearchRouteImport } from './routes/api/docs/search'
import { Route as ApiDocsAskRouteImport } from './routes/api/docs/ask'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSearchRoute = DocsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRemarkRoute = DocsRemarkRouteImport.update({
  id: '/remark',
  path: '/remark',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMethodologyRoute = DocsMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsLlmRoute = DocsLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsLintRoute = DocsLintRouteImport.update({
  id: '/lint',
  path: '/lint',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsConvertRoute = DocsConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsRoute = DocsComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesConnectDocsSiteRoute =
  DocsGuidesConnectDocsSiteRouteImport.update({
    id: '/guides/connect-docs-site',
    path: '/guides/connect-docs-site',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGuidesBundlePackageDocsRoute =
  DocsGuidesBundlePackageDocsRouteImport.update({
    id: '/guides/bundle-package-docs',
    path: '/guides/bundle-package-docs',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const ApiDocsSearchRoute = ApiDocsSearchRouteImport.update({
  id: '/api/docs/search',
  path: '/api/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsAskRoute = ApiDocsAskRouteImport.update({
  id: '/api/docs/ask',
  path: '/api/docs/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRoute
  '/docs/components': typeof DocsComponentsRoute
  '/docs/convert': typeof DocsConvertRoute
  '/docs/lint': typeof DocsLintRoute
  '/docs/llm': typeof DocsLlmRoute
  '/docs/methodology': typeof DocsMethodologyRoute
  '/docs/remark': typeof DocsRemarkRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/guides/bundle-package-docs': typeof DocsGuidesBundlePackageDocsRoute
  '/docs/guides/connect-docs-site': typeof DocsGuidesConnectDocsSiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRoute
  '/docs/components': typeof DocsComponentsRoute
  '/docs/convert': typeof DocsConvertRoute
  '/docs/lint': typeof DocsLintRoute
  '/docs/llm': typeof DocsLlmRoute
  '/docs/methodology': typeof DocsMethodologyRoute
  '/docs/remark': typeof DocsRemarkRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/guides/bundle-package-docs': typeof DocsGuidesBundlePackageDocsRoute
  '/docs/guides/connect-docs-site': typeof DocsGuidesConnectDocsSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRoute
  '/docs/components': typeof DocsComponentsRoute
  '/docs/convert': typeof DocsConvertRoute
  '/docs/lint': typeof DocsLintRoute
  '/docs/llm': typeof DocsLlmRoute
  '/docs/methodology': typeof DocsMethodologyRoute
  '/docs/remark': typeof DocsRemarkRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/guides/bundle-package-docs': typeof DocsGuidesBundlePackageDocsRoute
  '/docs/guides/connect-docs-site': typeof DocsGuidesConnectDocsSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/docs/components'
    | '/docs/convert'
    | '/docs/lint'
    | '/docs/llm'
    | '/docs/methodology'
    | '/docs/remark'
    | '/docs/search'
    | '/docs/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/guides/bundle-package-docs'
    | '/docs/guides/connect-docs-site'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/search'
    | '/docs/components'
    | '/docs/convert'
    | '/docs/lint'
    | '/docs/llm'
    | '/docs/methodology'
    | '/docs/remark'
    | '/docs/search'
    | '/docs'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/guides/bundle-package-docs'
    | '/docs/guides/connect-docs-site'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/docs/components'
    | '/docs/convert'
    | '/docs/lint'
    | '/docs/llm'
    | '/docs/methodology'
    | '/docs/remark'
    | '/docs/search'
    | '/docs/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/guides/bundle-package-docs'
    | '/docs/guides/connect-docs-site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  SearchRoute: typeof SearchRoute
  ApiDocsAskRoute: typeof ApiDocsAskRoute
  ApiDocsSearchRoute: typeof ApiDocsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/search': {
      id: '/docs/search'
      path: '/search'
      fullPath: '/docs/search'
      preLoaderRoute: typeof DocsSearchRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/remark': {
      id: '/docs/remark'
      path: '/remark'
      fullPath: '/docs/remark'
      preLoaderRoute: typeof DocsRemarkRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/methodology': {
      id: '/docs/methodology'
      path: '/methodology'
      fullPath: '/docs/methodology'
      preLoaderRoute: typeof DocsMethodologyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/llm': {
      id: '/docs/llm'
      path: '/llm'
      fullPath: '/docs/llm'
      preLoaderRoute: typeof DocsLlmRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/lint': {
      id: '/docs/lint'
      path: '/lint'
      fullPath: '/docs/lint'
      preLoaderRoute: typeof DocsLintRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/convert': {
      id: '/docs/convert'
      path: '/convert'
      fullPath: '/docs/convert'
      preLoaderRoute: typeof DocsConvertRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components': {
      id: '/docs/components'
      path: '/components'
      fullPath: '/docs/components'
      preLoaderRoute: typeof DocsComponentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/connect-docs-site': {
      id: '/docs/guides/connect-docs-site'
      path: '/guides/connect-docs-site'
      fullPath: '/docs/guides/connect-docs-site'
      preLoaderRoute: typeof DocsGuidesConnectDocsSiteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/bundle-package-docs': {
      id: '/docs/guides/bundle-package-docs'
      path: '/guides/bundle-package-docs'
      fullPath: '/docs/guides/bundle-package-docs'
      preLoaderRoute: typeof DocsGuidesBundlePackageDocsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/api/docs/search': {
      id: '/api/docs/search'
      path: '/api/docs/search'
      fullPath: '/api/docs/search'
      preLoaderRoute: typeof ApiDocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/ask': {
      id: '/api/docs/ask'
      path: '/api/docs/ask'
      fullPath: '/api/docs/ask'
      preLoaderRoute: typeof ApiDocsAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsComponentsRoute: typeof DocsComponentsRoute
  DocsConvertRoute: typeof DocsConvertRoute
  DocsLintRoute: typeof DocsLintRoute
  DocsLlmRoute: typeof DocsLlmRoute
  DocsMethodologyRoute: typeof DocsMethodologyRoute
  DocsRemarkRoute: typeof DocsRemarkRoute
  DocsSearchRoute: typeof DocsSearchRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsGuidesBundlePackageDocsRoute: typeof DocsGuidesBundlePackageDocsRoute
  DocsGuidesConnectDocsSiteRoute: typeof DocsGuidesConnectDocsSiteRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsComponentsRoute: DocsComponentsRoute,
  DocsConvertRoute: DocsConvertRoute,
  DocsLintRoute: DocsLintRoute,
  DocsLlmRoute: DocsLlmRoute,
  DocsMethodologyRoute: DocsMethodologyRoute,
  DocsRemarkRoute: DocsRemarkRoute,
  DocsSearchRoute: DocsSearchRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsGuidesBundlePackageDocsRoute: DocsGuidesBundlePackageDocsRoute,
  DocsGuidesConnectDocsSiteRoute: DocsGuidesConnectDocsSiteRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  SearchRoute: SearchRoute,
  ApiDocsAskRoute: ApiDocsAskRoute,
  ApiDocsSearchRoute: ApiDocsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
