/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as SearchVercelRouteImport } from './routes/search/vercel'
import { Route as SearchTanstackRouteImport } from './routes/search/tanstack'
import { Route as SearchCloudflareRouteImport } from './routes/search/cloudflare'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsMethodologyRouteImport } from './routes/docs/methodology'
import { Route as DocsHowItWorksRouteImport } from './routes/docs/how-it-works'
import { Route as DocsReferenceSearchRouteImport } from './routes/docs/reference/search'
import { Route as DocsReferenceRemarkRouteImport } from './routes/docs/reference/remark'
import { Route as DocsReferenceLlmRouteImport } from './routes/docs/reference/llm'
import { Route as DocsReferenceLintRouteImport } from './routes/docs/reference/lint'
import { Route as DocsReferenceConvertRouteImport } from './routes/docs/reference/convert'
import { Route as DocsReferenceCliRouteImport } from './routes/docs/reference/cli'
import { Route as DocsBuildValidateInCiRouteImport } from './routes/docs/build/validate-in-ci'
import { Route as DocsBuildConnectDocsSiteRouteImport } from './routes/docs/build/connect-docs-site'
import { Route as DocsBuildBundlePackageDocsRouteImport } from './routes/docs/build/bundle-package-docs'
import { Route as DocsAuthoringFrontmatterRouteImport } from './routes/docs/authoring/frontmatter'
import { Route as DocsAuthoringComponentsRouteImport } from './routes/docs/authoring/components'
import { Route as ApiDocsSearchRouteImport } from './routes/api/docs/search'
import { Route as ApiDocsAskRouteImport } from './routes/api/docs/ask'
import { Route as ApiDocsAskVercelRouteImport } from './routes/api/docs/ask/vercel'
import { Route as ApiDocsAskTanstackRouteImport } from './routes/api/docs/ask/tanstack'
import { Route as ApiDocsAskCloudflareRouteImport } from './routes/api/docs/ask/cloudflare'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const SearchVercelRoute = SearchVercelRouteImport.update({
  id: '/vercel',
  path: '/vercel',
  getParentRoute: () => SearchRoute,
} as any)
const SearchTanstackRoute = SearchTanstackRouteImport.update({
  id: '/tanstack',
  path: '/tanstack',
  getParentRoute: () => SearchRoute,
} as any)
const SearchCloudflareRoute = SearchCloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => SearchRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMethodologyRoute = DocsMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceSearchRoute = DocsReferenceSearchRouteImport.update({
  id: '/reference/search',
  path: '/reference/search',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceRemarkRoute = DocsReferenceRemarkRouteImport.update({
  id: '/reference/remark',
  path: '/reference/remark',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceLlmRoute = DocsReferenceLlmRouteImport.update({
  id: '/reference/llm',
  path: '/reference/llm',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceLintRoute = DocsReferenceLintRouteImport.update({
  id: '/reference/lint',
  path: '/reference/lint',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceConvertRoute = DocsReferenceConvertRouteImport.update({
  id: '/reference/convert',
  path: '/reference/convert',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReferenceCliRoute = DocsReferenceCliRouteImport.update({
  id: '/reference/cli',
  path: '/reference/cli',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsBuildValidateInCiRoute = DocsBuildValidateInCiRouteImport.update({
  id: '/build/validate-in-ci',
  path: '/build/validate-in-ci',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsBuildConnectDocsSiteRoute =
  DocsBuildConnectDocsSiteRouteImport.update({
    id: '/build/connect-docs-site',
    path: '/build/connect-docs-site',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsBuildBundlePackageDocsRoute =
  DocsBuildBundlePackageDocsRouteImport.update({
    id: '/build/bundle-package-docs',
    path: '/build/bundle-package-docs',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAuthoringFrontmatterRoute =
  DocsAuthoringFrontmatterRouteImport.update({
    id: '/authoring/frontmatter',
    path: '/authoring/frontmatter',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsAuthoringComponentsRoute = DocsAuthoringComponentsRouteImport.update({
  id: '/authoring/components',
  path: '/authoring/components',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ApiDocsSearchRoute = ApiDocsSearchRouteImport.update({
  id: '/api/docs/search',
  path: '/api/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsAskRoute = ApiDocsAskRouteImport.update({
  id: '/api/docs/ask',
  path: '/api/docs/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsAskVercelRoute = ApiDocsAskVercelRouteImport.update({
  id: '/vercel',
  path: '/vercel',
  getParentRoute: () => ApiDocsAskRoute,
} as any)
const ApiDocsAskTanstackRoute = ApiDocsAskTanstackRouteImport.update({
  id: '/tanstack',
  path: '/tanstack',
  getParentRoute: () => ApiDocsAskRoute,
} as any)
const ApiDocsAskCloudflareRoute = ApiDocsAskCloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => ApiDocsAskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRouteWithChildren
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/methodology': typeof DocsMethodologyRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/search/cloudflare': typeof SearchCloudflareRoute
  '/search/tanstack': typeof SearchTanstackRoute
  '/search/vercel': typeof SearchVercelRoute
  '/docs/': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRouteWithChildren
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/authoring/components': typeof DocsAuthoringComponentsRoute
  '/docs/authoring/frontmatter': typeof DocsAuthoringFrontmatterRoute
  '/docs/build/bundle-package-docs': typeof DocsBuildBundlePackageDocsRoute
  '/docs/build/connect-docs-site': typeof DocsBuildConnectDocsSiteRoute
  '/docs/build/validate-in-ci': typeof DocsBuildValidateInCiRoute
  '/docs/reference/cli': typeof DocsReferenceCliRoute
  '/docs/reference/convert': typeof DocsReferenceConvertRoute
  '/docs/reference/lint': typeof DocsReferenceLintRoute
  '/docs/reference/llm': typeof DocsReferenceLlmRoute
  '/docs/reference/remark': typeof DocsReferenceRemarkRoute
  '/docs/reference/search': typeof DocsReferenceSearchRoute
  '/api/docs/ask/cloudflare': typeof ApiDocsAskCloudflareRoute
  '/api/docs/ask/tanstack': typeof ApiDocsAskTanstackRoute
  '/api/docs/ask/vercel': typeof ApiDocsAskVercelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRouteWithChildren
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/methodology': typeof DocsMethodologyRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/search/cloudflare': typeof SearchCloudflareRoute
  '/search/tanstack': typeof SearchTanstackRoute
  '/search/vercel': typeof SearchVercelRoute
  '/docs': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRouteWithChildren
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/authoring/components': typeof DocsAuthoringComponentsRoute
  '/docs/authoring/frontmatter': typeof DocsAuthoringFrontmatterRoute
  '/docs/build/bundle-package-docs': typeof DocsBuildBundlePackageDocsRoute
  '/docs/build/connect-docs-site': typeof DocsBuildConnectDocsSiteRoute
  '/docs/build/validate-in-ci': typeof DocsBuildValidateInCiRoute
  '/docs/reference/cli': typeof DocsReferenceCliRoute
  '/docs/reference/convert': typeof DocsReferenceConvertRoute
  '/docs/reference/lint': typeof DocsReferenceLintRoute
  '/docs/reference/llm': typeof DocsReferenceLlmRoute
  '/docs/reference/remark': typeof DocsReferenceRemarkRoute
  '/docs/reference/search': typeof DocsReferenceSearchRoute
  '/api/docs/ask/cloudflare': typeof ApiDocsAskCloudflareRoute
  '/api/docs/ask/tanstack': typeof ApiDocsAskTanstackRoute
  '/api/docs/ask/vercel': typeof ApiDocsAskVercelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRouteWithChildren
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/methodology': typeof DocsMethodologyRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/search/cloudflare': typeof SearchCloudflareRoute
  '/search/tanstack': typeof SearchTanstackRoute
  '/search/vercel': typeof SearchVercelRoute
  '/docs/': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRouteWithChildren
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/authoring/components': typeof DocsAuthoringComponentsRoute
  '/docs/authoring/frontmatter': typeof DocsAuthoringFrontmatterRoute
  '/docs/build/bundle-package-docs': typeof DocsBuildBundlePackageDocsRoute
  '/docs/build/connect-docs-site': typeof DocsBuildConnectDocsSiteRoute
  '/docs/build/validate-in-ci': typeof DocsBuildValidateInCiRoute
  '/docs/reference/cli': typeof DocsReferenceCliRoute
  '/docs/reference/convert': typeof DocsReferenceConvertRoute
  '/docs/reference/lint': typeof DocsReferenceLintRoute
  '/docs/reference/llm': typeof DocsReferenceLlmRoute
  '/docs/reference/remark': typeof DocsReferenceRemarkRoute
  '/docs/reference/search': typeof DocsReferenceSearchRoute
  '/api/docs/ask/cloudflare': typeof ApiDocsAskCloudflareRoute
  '/api/docs/ask/tanstack': typeof ApiDocsAskTanstackRoute
  '/api/docs/ask/vercel': typeof ApiDocsAskVercelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/docs/how-it-works'
    | '/docs/methodology'
    | '/docs/quickstart'
    | '/search/cloudflare'
    | '/search/tanstack'
    | '/search/vercel'
    | '/docs/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/authoring/components'
    | '/docs/authoring/frontmatter'
    | '/docs/build/bundle-package-docs'
    | '/docs/build/connect-docs-site'
    | '/docs/build/validate-in-ci'
    | '/docs/reference/cli'
    | '/docs/reference/convert'
    | '/docs/reference/lint'
    | '/docs/reference/llm'
    | '/docs/reference/remark'
    | '/docs/reference/search'
    | '/api/docs/ask/cloudflare'
    | '/api/docs/ask/tanstack'
    | '/api/docs/ask/vercel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/search'
    | '/docs/how-it-works'
    | '/docs/methodology'
    | '/docs/quickstart'
    | '/search/cloudflare'
    | '/search/tanstack'
    | '/search/vercel'
    | '/docs'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/authoring/components'
    | '/docs/authoring/frontmatter'
    | '/docs/build/bundle-package-docs'
    | '/docs/build/connect-docs-site'
    | '/docs/build/validate-in-ci'
    | '/docs/reference/cli'
    | '/docs/reference/convert'
    | '/docs/reference/lint'
    | '/docs/reference/llm'
    | '/docs/reference/remark'
    | '/docs/reference/search'
    | '/api/docs/ask/cloudflare'
    | '/api/docs/ask/tanstack'
    | '/api/docs/ask/vercel'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/docs/how-it-works'
    | '/docs/methodology'
    | '/docs/quickstart'
    | '/search/cloudflare'
    | '/search/tanstack'
    | '/search/vercel'
    | '/docs/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/authoring/components'
    | '/docs/authoring/frontmatter'
    | '/docs/build/bundle-package-docs'
    | '/docs/build/connect-docs-site'
    | '/docs/build/validate-in-ci'
    | '/docs/reference/cli'
    | '/docs/reference/convert'
    | '/docs/reference/lint'
    | '/docs/reference/llm'
    | '/docs/reference/remark'
    | '/docs/reference/search'
    | '/api/docs/ask/cloudflare'
    | '/api/docs/ask/tanstack'
    | '/api/docs/ask/vercel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  SearchRoute: typeof SearchRouteWithChildren
  ApiDocsAskRoute: typeof ApiDocsAskRouteWithChildren
  ApiDocsSearchRoute: typeof ApiDocsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/search/vercel': {
      id: '/search/vercel'
      path: '/vercel'
      fullPath: '/search/vercel'
      preLoaderRoute: typeof SearchVercelRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/tanstack': {
      id: '/search/tanstack'
      path: '/tanstack'
      fullPath: '/search/tanstack'
      preLoaderRoute: typeof SearchTanstackRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/cloudflare': {
      id: '/search/cloudflare'
      path: '/cloudflare'
      fullPath: '/search/cloudflare'
      preLoaderRoute: typeof SearchCloudflareRouteImport
      parentRoute: typeof SearchRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/methodology': {
      id: '/docs/methodology'
      path: '/methodology'
      fullPath: '/docs/methodology'
      preLoaderRoute: typeof DocsMethodologyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/how-it-works': {
      id: '/docs/how-it-works'
      path: '/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reference/search': {
      id: '/docs/reference/search'
      path: '/reference/search'
      fullPath: '/docs/reference/search'
      preLoaderRoute: typeof DocsReferenceSearchRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reference/remark': {
      id: '/docs/reference/remark'
      path: '/reference/remark'
      fullPath: '/docs/reference/remark'
      preLoaderRoute: typeof DocsReferenceRemarkRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reference/llm': {
      id: '/docs/reference/llm'
      path: '/reference/llm'
      fullPath: '/docs/reference/llm'
      preLoaderRoute: typeof DocsReferenceLlmRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reference/lint': {
      id: '/docs/reference/lint'
      path: '/reference/lint'
      fullPath: '/docs/reference/lint'
      preLoaderRoute: typeof DocsReferenceLintRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reference/convert': {
      id: '/docs/reference/convert'
      path: '/reference/convert'
      fullPath: '/docs/reference/convert'
      preLoaderRoute: typeof DocsReferenceConvertRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/reference/cli': {
      id: '/docs/reference/cli'
      path: '/reference/cli'
      fullPath: '/docs/reference/cli'
      preLoaderRoute: typeof DocsReferenceCliRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/build/validate-in-ci': {
      id: '/docs/build/validate-in-ci'
      path: '/build/validate-in-ci'
      fullPath: '/docs/build/validate-in-ci'
      preLoaderRoute: typeof DocsBuildValidateInCiRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/build/connect-docs-site': {
      id: '/docs/build/connect-docs-site'
      path: '/build/connect-docs-site'
      fullPath: '/docs/build/connect-docs-site'
      preLoaderRoute: typeof DocsBuildConnectDocsSiteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/build/bundle-package-docs': {
      id: '/docs/build/bundle-package-docs'
      path: '/build/bundle-package-docs'
      fullPath: '/docs/build/bundle-package-docs'
      preLoaderRoute: typeof DocsBuildBundlePackageDocsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/authoring/frontmatter': {
      id: '/docs/authoring/frontmatter'
      path: '/authoring/frontmatter'
      fullPath: '/docs/authoring/frontmatter'
      preLoaderRoute: typeof DocsAuthoringFrontmatterRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/authoring/components': {
      id: '/docs/authoring/components'
      path: '/authoring/components'
      fullPath: '/docs/authoring/components'
      preLoaderRoute: typeof DocsAuthoringComponentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/api/docs/search': {
      id: '/api/docs/search'
      path: '/api/docs/search'
      fullPath: '/api/docs/search'
      preLoaderRoute: typeof ApiDocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/ask': {
      id: '/api/docs/ask'
      path: '/api/docs/ask'
      fullPath: '/api/docs/ask'
      preLoaderRoute: typeof ApiDocsAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/ask/vercel': {
      id: '/api/docs/ask/vercel'
      path: '/vercel'
      fullPath: '/api/docs/ask/vercel'
      preLoaderRoute: typeof ApiDocsAskVercelRouteImport
      parentRoute: typeof ApiDocsAskRoute
    }
    '/api/docs/ask/tanstack': {
      id: '/api/docs/ask/tanstack'
      path: '/tanstack'
      fullPath: '/api/docs/ask/tanstack'
      preLoaderRoute: typeof ApiDocsAskTanstackRouteImport
      parentRoute: typeof ApiDocsAskRoute
    }
    '/api/docs/ask/cloudflare': {
      id: '/api/docs/ask/cloudflare'
      path: '/cloudflare'
      fullPath: '/api/docs/ask/cloudflare'
      preLoaderRoute: typeof ApiDocsAskCloudflareRouteImport
      parentRoute: typeof ApiDocsAskRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsMethodologyRoute: typeof DocsMethodologyRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsAuthoringComponentsRoute: typeof DocsAuthoringComponentsRoute
  DocsAuthoringFrontmatterRoute: typeof DocsAuthoringFrontmatterRoute
  DocsBuildBundlePackageDocsRoute: typeof DocsBuildBundlePackageDocsRoute
  DocsBuildConnectDocsSiteRoute: typeof DocsBuildConnectDocsSiteRoute
  DocsBuildValidateInCiRoute: typeof DocsBuildValidateInCiRoute
  DocsReferenceCliRoute: typeof DocsReferenceCliRoute
  DocsReferenceConvertRoute: typeof DocsReferenceConvertRoute
  DocsReferenceLintRoute: typeof DocsReferenceLintRoute
  DocsReferenceLlmRoute: typeof DocsReferenceLlmRoute
  DocsReferenceRemarkRoute: typeof DocsReferenceRemarkRoute
  DocsReferenceSearchRoute: typeof DocsReferenceSearchRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsMethodologyRoute: DocsMethodologyRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsAuthoringComponentsRoute: DocsAuthoringComponentsRoute,
  DocsAuthoringFrontmatterRoute: DocsAuthoringFrontmatterRoute,
  DocsBuildBundlePackageDocsRoute: DocsBuildBundlePackageDocsRoute,
  DocsBuildConnectDocsSiteRoute: DocsBuildConnectDocsSiteRoute,
  DocsBuildValidateInCiRoute: DocsBuildValidateInCiRoute,
  DocsReferenceCliRoute: DocsReferenceCliRoute,
  DocsReferenceConvertRoute: DocsReferenceConvertRoute,
  DocsReferenceLintRoute: DocsReferenceLintRoute,
  DocsReferenceLlmRoute: DocsReferenceLlmRoute,
  DocsReferenceRemarkRoute: DocsReferenceRemarkRoute,
  DocsReferenceSearchRoute: DocsReferenceSearchRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface SearchRouteChildren {
  SearchCloudflareRoute: typeof SearchCloudflareRoute
  SearchTanstackRoute: typeof SearchTanstackRoute
  SearchVercelRoute: typeof SearchVercelRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchCloudflareRoute: SearchCloudflareRoute,
  SearchTanstackRoute: SearchTanstackRoute,
  SearchVercelRoute: SearchVercelRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface ApiDocsAskRouteChildren {
  ApiDocsAskCloudflareRoute: typeof ApiDocsAskCloudflareRoute
  ApiDocsAskTanstackRoute: typeof ApiDocsAskTanstackRoute
  ApiDocsAskVercelRoute: typeof ApiDocsAskVercelRoute
}

const ApiDocsAskRouteChildren: ApiDocsAskRouteChildren = {
  ApiDocsAskCloudflareRoute: ApiDocsAskCloudflareRoute,
  ApiDocsAskTanstackRoute: ApiDocsAskTanstackRoute,
  ApiDocsAskVercelRoute: ApiDocsAskVercelRoute,
}

const ApiDocsAskRouteWithChildren = ApiDocsAskRoute._addFileChildren(
  ApiDocsAskRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  SearchRoute: SearchRouteWithChildren,
  ApiDocsAskRoute: ApiDocsAskRouteWithChildren,
  ApiDocsSearchRoute: ApiDocsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
