/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSearchRouteImport } from './routes/docs/search'
import { Route as DocsGuidesQuickstartRouteImport } from './routes/docs/guides/quickstart'
import { Route as DocsGuidesComponentsFixtureRouteImport } from './routes/docs/guides/components-fixture'
import { Route as ApiDocsSearchRouteImport } from './routes/api/docs/search'
import { Route as ApiDocsAskRouteImport } from './routes/api/docs/ask'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSearchRoute = DocsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesQuickstartRoute = DocsGuidesQuickstartRouteImport.update({
  id: '/guides/quickstart',
  path: '/guides/quickstart',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesComponentsFixtureRoute =
  DocsGuidesComponentsFixtureRouteImport.update({
    id: '/guides/components-fixture',
    path: '/guides/components-fixture',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const ApiDocsSearchRoute = ApiDocsSearchRouteImport.update({
  id: '/api/docs/search',
  path: '/api/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsAskRoute = ApiDocsAskRouteImport.update({
  id: '/api/docs/ask',
  path: '/api/docs/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/guides/components-fixture': typeof DocsGuidesComponentsFixtureRoute
  '/docs/guides/quickstart': typeof DocsGuidesQuickstartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/guides/components-fixture': typeof DocsGuidesComponentsFixtureRoute
  '/docs/guides/quickstart': typeof DocsGuidesQuickstartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/search': typeof SearchRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/': typeof DocsIndexRoute
  '/api/docs/ask': typeof ApiDocsAskRoute
  '/api/docs/search': typeof ApiDocsSearchRoute
  '/docs/guides/components-fixture': typeof DocsGuidesComponentsFixtureRoute
  '/docs/guides/quickstart': typeof DocsGuidesQuickstartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/docs/search'
    | '/docs/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/guides/components-fixture'
    | '/docs/guides/quickstart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/search'
    | '/docs/search'
    | '/docs'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/guides/components-fixture'
    | '/docs/guides/quickstart'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/search'
    | '/docs/search'
    | '/docs/'
    | '/api/docs/ask'
    | '/api/docs/search'
    | '/docs/guides/components-fixture'
    | '/docs/guides/quickstart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  SearchRoute: typeof SearchRoute
  ApiDocsAskRoute: typeof ApiDocsAskRoute
  ApiDocsSearchRoute: typeof ApiDocsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/search': {
      id: '/docs/search'
      path: '/search'
      fullPath: '/docs/search'
      preLoaderRoute: typeof DocsSearchRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/quickstart': {
      id: '/docs/guides/quickstart'
      path: '/guides/quickstart'
      fullPath: '/docs/guides/quickstart'
      preLoaderRoute: typeof DocsGuidesQuickstartRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/components-fixture': {
      id: '/docs/guides/components-fixture'
      path: '/guides/components-fixture'
      fullPath: '/docs/guides/components-fixture'
      preLoaderRoute: typeof DocsGuidesComponentsFixtureRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/api/docs/search': {
      id: '/api/docs/search'
      path: '/api/docs/search'
      fullPath: '/api/docs/search'
      preLoaderRoute: typeof ApiDocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs/ask': {
      id: '/api/docs/ask'
      path: '/api/docs/ask'
      fullPath: '/api/docs/ask'
      preLoaderRoute: typeof ApiDocsAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsSearchRoute: typeof DocsSearchRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsGuidesComponentsFixtureRoute: typeof DocsGuidesComponentsFixtureRoute
  DocsGuidesQuickstartRoute: typeof DocsGuidesQuickstartRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSearchRoute: DocsSearchRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsGuidesComponentsFixtureRoute: DocsGuidesComponentsFixtureRoute,
  DocsGuidesQuickstartRoute: DocsGuidesQuickstartRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  SearchRoute: SearchRoute,
  ApiDocsAskRoute: ApiDocsAskRoute,
  ApiDocsSearchRoute: ApiDocsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
