// Build-time MDX bridge for the synced leadtype docs.
//
// Scans `.leadtype/docs` for actual `.mdx` files (not the manifest, which can
// list phantom group-landing pages) and emits an import map keyed by route slug
// → a dynamic import of the synced source `.mdx`. `@next/mdx` compiles each at
// build (next.config.mjs), resolving <ExtractedTypeTable>/<include> via
// leadtype's source preset. Build-time counterpart to the Vite example's
// import.meta.glob.

import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const appDir = process.cwd();
const docsDir = path.resolve(appDir, ".leadtype/docs");
const mapFile = path.join(appDir, "app/generated/docs-mdx-map.ts");
const INDEX_SUFFIX = /\/index$/;

async function walk(dir, base = "") {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      out.push(...(await walk(path.join(dir, entry.name), rel)));
    } else if (entry.name.endsWith(".mdx")) {
      out.push(rel.slice(0, -".mdx".length));
    }
  }
  return out;
}

const relPaths = (await walk(docsDir)).sort();
const entries = relPaths.map((rel) => {
  const slug = rel === "index" ? "" : rel.replace(INDEX_SUFFIX, "");
  return [slug, `../../.leadtype/docs/${rel}.mdx`];
});

await mkdir(path.dirname(mapFile), { recursive: true });
const importLines = entries
  .map(
    ([slug, spec]) =>
      `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(spec)}),`
  )
  .join("\n");
const slugList = entries.map(([slug]) => JSON.stringify(slug)).join(", ");

await writeFile(
  mapFile,
  `/* Generated by scripts/build-mdx-map.mjs — do not edit. */
import type { ComponentType } from "react";

type MdxModule = { default: ComponentType<Record<string, unknown>> };

const mdxModules: Record<string, () => Promise<MdxModule>> = {
${importLines}
};

/** Route slugs that have a backing MDX file (drives generateStaticParams). */
export const mdxSlugs: string[] = [${slugList}];

export function loadDocsMdx(slug: string[] = []): Promise<MdxModule> | undefined {
  return mdxModules[slug.join("/")]?.();
}
`
);
