import type { DocsNavigation, DocsNavigationGroup } from "@inth/docs/llm";
import docsNavigation from "@/generated/docs-nav.json";

const navigation = docsNavigation as DocsNavigation;

export interface NavigationRoute {
  description: string;
  label: string;
  to: string;
}

/** Top-level header nav. */
export const navigationRoutes: NavigationRoute[] = [
  {
    label: "Home",
    to: "/",
    description: "Developer dashboard for the package.",
  },
  {
    label: "Docs",
    to: "/docs",
    description: "Reference docs rendered from /docs MDX source.",
  },
  {
    label: "Recipes",
    to: "/playground",
    description: "Guided integration recipes with live components.",
  },
  {
    label: "Live Search",
    to: "/search",
    description: "Local search and optional source-grounded answers.",
  },
];

export interface DocsSidebarLink {
  label: string;
  to: string;
}

export interface DocsSidebarSection {
  description?: string;
  links: DocsSidebarLink[];
  title: string;
}

function flattenGroupPages(group: DocsNavigationGroup): DocsSidebarLink[] {
  const direct = group.pages.map((page) => ({
    label: page.title,
    to: page.urlPath,
  }));
  const nested = group.children.flatMap(flattenGroupPages);
  return [...direct, ...nested];
}

/**
 * Sidebar nav for the /docs surface, derived from the build-time `docs-nav.json`
 * manifest. The manifest is generated by `apps/example/scripts/llm-generate.ts`
 * (which calls `resolveDocsNavigation` from `@inth/docs/llm`) and reflects the
 * `group:` frontmatter on each `/docs/*.mdx`. This is exactly how an external
 * consumer like c15t/c15t would wire its sidebar.
 */
export const docsSidebarSections: DocsSidebarSection[] = navigation.groups.map(
  (group) => ({
    title: group.title,
    description: group.description,
    links: flattenGroupPages(group),
  })
);

export interface PackageSurface {
  description: string;
  importPath: string;
  lifecycle: "runtime" | "build time" | "optional runtime";
}

export const packageSurfaces: PackageSurface[] = [
  {
    importPath: "@inth/docs",
    lifecycle: "build time",
    description: "Root export with `defineDocsConfig` and shared types.",
  },
  {
    importPath: "@inth/docs/remark",
    lifecycle: "build time",
    description: "remark plugins and `defaultRemarkPlugins`.",
  },
  {
    importPath: "@inth/docs/convert",
    lifecycle: "build time",
    description: "MDX-to-markdown conversion APIs.",
  },
  {
    importPath: "@inth/docs/llm",
    lifecycle: "build time",
    description: "`llms.txt` and full-context generation.",
  },
  {
    importPath: "@inth/docs/search",
    lifecycle: "runtime",
    description:
      "Search runtime, content readers, guards, and rate limiter helpers.",
  },
  {
    importPath: "@inth/docs/search/node",
    lifecycle: "build time",
    description: "Node-only `generateDocsSearchFiles`.",
  },
  {
    importPath: "@inth/docs/search/vercel",
    lifecycle: "optional runtime",
    description: "Vercel AI Gateway / AI SDK answer streaming and bash tools.",
  },
  {
    importPath: "@inth/docs/search/tanstack",
    lifecycle: "optional runtime",
    description: "TanStack AI answer streaming and native docs bash tools.",
  },
  {
    importPath: "@inth/docs/search/cloudflare",
    lifecycle: "optional runtime",
    description:
      "Cloudflare AI Gateway / Workers AI adapter helpers and docs bash tools.",
  },
  {
    importPath: "@inth/docs/lint",
    lifecycle: "build time",
    description: "Lint APIs and the `inth-docs-lint` CLI.",
  },
];

export type SmokeCoverage =
  | "agent docs"
  | "browser hydration"
  | "pipeline conversion"
  | "runtime render"
  | "search/API";

export const componentMatrix: Array<{
  coverage: SmokeCoverage[];
  name: string;
  note: string;
}> = [
  {
    name: "Callout",
    coverage: ["runtime render", "agent docs"],
    note: "App-owned semantic note blocks rendered from MDX.",
  },
  {
    name: "Card / Cards",
    coverage: ["runtime render", "agent docs"],
    note: "App-owned card grids rendered directly from authoring MDX.",
  },
  {
    name: "Steps / Step",
    coverage: ["runtime render", "agent docs"],
    note: "App-owned walkthrough content rendered as semantic ordered lists.",
  },
  {
    name: "Tabs / Tab",
    coverage: ["runtime render", "browser hydration", "agent docs"],
    note: "App-owned tab panels with keyboard navigation in the browser.",
  },
  {
    name: "CommandTabs",
    coverage: ["runtime render", "browser hydration", "agent docs"],
    note: "App-owned command switcher for install, run, or create commands.",
  },
  {
    name: "Accordion / AccordionItem",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Collapsible details that still flatten into generated markdown.",
  },
  {
    name: "Example",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Data-driven preview and source examples for authored MDX.",
  },
  {
    name: "TopicSwitcher",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Reader-facing navigation across equivalent docs topics.",
  },
  {
    name: "Selector",
    coverage: ["runtime render", "browser hydration"],
    note: "App-owned selector drives the guided recipe playground.",
  },
  {
    name: "Mermaid",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "App-owned code-block fallback that consumers can enhance later.",
  },
  {
    name: "TypeTable",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "App-owned prop tables rendered in-browser from MDX props.",
  },
  {
    name: "ExtractedTypeTable",
    coverage: ["runtime render", "pipeline conversion"],
    note: "App-owned rendering for type data still extracted by the pipeline.",
  },
  {
    name: "Search APIs",
    coverage: ["search/API", "browser hydration"],
    note: "Generated static index, server routes, and optional AI answer streaming.",
  },
];
