import type {
  DocsNavigation,
  DocsNavigationGroup,
  DocsNavigationPage,
} from "leadtype/llm";
import docsNavigation from "@/generated/docs-nav.json";

const TRAILING_SLASH_PATTERN = /\/$/;

export const docsNavigationManifest =
  docsNavigation as unknown as DocsNavigation;

export interface NavigationRoute {
  description: string;
  docsGroupKey?: string;
  label: string;
  to: string;
}

function firstPageInGroup(
  group: DocsNavigationGroup
): DocsNavigationPage | undefined {
  const directPage = group.pages[0];
  if (directPage) {
    return directPage;
  }

  for (const child of group.children) {
    const page = firstPageInGroup(child);
    if (page) {
      return page;
    }
  }
}

function groupKey(group: DocsNavigationGroup): string {
  return group.segmentPath.join("/");
}

function groupContainsPath(
  group: DocsNavigationGroup,
  pathname: string
): boolean {
  if (group.pages.some((page) => page.urlPath === pathname)) {
    return true;
  }

  return group.children.some((child) => groupContainsPath(child, pathname));
}

function findTopNavigationGroup(
  pathname: string
): DocsNavigationGroup | undefined {
  const normalizedPathname =
    pathname.length > 1
      ? pathname.replace(TRAILING_SLASH_PATTERN, "")
      : pathname;

  return docsNavigationManifest.groups.find((group) =>
    groupContainsPath(group, normalizedPathname)
  );
}

const docsTopNavigationRoutes: NavigationRoute[] =
  docsNavigationManifest.groups.flatMap((group) => {
    const page = firstPageInGroup(group);
    if (!page) {
      return [];
    }

    return [
      {
        label: group.title,
        to: page.urlPath,
        description:
          group.description ??
          `${group.title} documentation rendered from the MDX source.`,
        docsGroupKey: groupKey(group),
      },
    ];
  });

/** Top-level header nav. Root docs nav nodes become docs surface tabs. */
export const navigationRoutes: NavigationRoute[] = [
  ...docsTopNavigationRoutes,
  {
    label: "Recipes",
    to: "/playground",
    description: "Guided integration recipes with live components.",
  },
  {
    label: "Live Search",
    to: "/search",
    description: "Local search and optional source-grounded answers.",
  },
];

export function isNavigationRouteActive(
  pathname: string,
  route: NavigationRoute
): boolean {
  if (route.docsGroupKey) {
    const activeGroup = findTopNavigationGroup(pathname);
    return activeGroup ? groupKey(activeGroup) === route.docsGroupKey : false;
  }

  return pathname === route.to;
}

export interface DocsSidebarLink {
  label: string;
  to: string;
}

export interface DocsSidebarSection {
  description?: string;
  links: DocsSidebarLink[];
  title: string;
}

function flattenGroupPages(group: DocsNavigationGroup): DocsSidebarLink[] {
  const direct = group.pages.map((page) => ({
    label: page.title,
    to: page.urlPath,
  }));
  const nested = group.children.flatMap(flattenGroupPages);
  return [...direct, ...nested];
}

function sectionsForGroup(group: DocsNavigationGroup): DocsSidebarSection[] {
  const directLinks = group.pages.map((page) => ({
    label: page.title,
    to: page.urlPath,
  }));
  const directSection =
    directLinks.length > 0
      ? [
          {
            title: group.title,
            description: group.description,
            links: directLinks,
          },
        ]
      : [];
  const childSections = group.children.map((child) => ({
    title: child.title,
    description: child.description,
    links: flattenGroupPages(child),
  }));

  return [...directSection, ...childSections].filter(
    (section) => section.links.length > 0
  );
}

/**
 * Sidebar nav for the /docs surface, derived from the build-time `docs-nav.json`
 * manifest. The manifest is generated by `apps/example/scripts/llm-generate.ts`
 * (which calls `resolveDocsNavigation` from `leadtype/llm`). Root nav nodes are
 * header tabs; the active root node's children become sidebar sections.
 */
export function getDocsSidebarSections(pathname: string): DocsSidebarSection[] {
  const activeGroup =
    findTopNavigationGroup(pathname) ?? docsNavigationManifest.groups[0];
  return activeGroup ? sectionsForGroup(activeGroup) : [];
}

function findPageInGroup(
  group: DocsNavigationGroup,
  pathname: string
): DocsNavigationPage | undefined {
  const directPage = group.pages.find((page) => page.urlPath === pathname);
  if (directPage) {
    return directPage;
  }

  for (const child of group.children) {
    const page = findPageInGroup(child, pathname);
    if (page) {
      return page;
    }
  }
}

export function findDocsNavigationPage(pathname: string) {
  const normalizedPathname =
    pathname.length > 1
      ? pathname.replace(TRAILING_SLASH_PATTERN, "")
      : pathname;

  for (const group of docsNavigationManifest.groups) {
    const page = findPageInGroup(group, normalizedPathname);
    if (page) {
      return page;
    }
  }

  return docsNavigationManifest.ungrouped.find(
    (page) => page.urlPath === normalizedPathname
  );
}

export interface PackageSurface {
  description: string;
  importPath: string;
  lifecycle: "runtime" | "build time" | "optional runtime";
}

export const packageSurfaces: PackageSurface[] = [
  {
    importPath: "leadtype",
    lifecycle: "build time",
    description: "Root export with `defineDocsConfig` and shared types.",
  },
  {
    importPath: "leadtype/remark",
    lifecycle: "build time",
    description: "remark plugins and `defaultRemarkPlugins`.",
  },
  {
    importPath: "leadtype/convert",
    lifecycle: "build time",
    description: "MDX-to-markdown conversion APIs.",
  },
  {
    importPath: "leadtype/llm",
    lifecycle: "build time",
    description: "`llms.txt` and full-context generation.",
  },
  {
    importPath: "leadtype/search",
    lifecycle: "runtime",
    description:
      "Search runtime, content readers, guards, and rate limiter helpers.",
  },
  {
    importPath: "leadtype/search/node",
    lifecycle: "build time",
    description: "Node-only `generateDocsSearchFiles`.",
  },
  {
    importPath: "leadtype/search/vercel",
    lifecycle: "optional runtime",
    description: "Vercel AI Gateway / AI SDK answer streaming and bash tools.",
  },
  {
    importPath: "leadtype/search/tanstack",
    lifecycle: "optional runtime",
    description: "TanStack AI answer streaming and native docs bash tools.",
  },
  {
    importPath: "leadtype/search/cloudflare",
    lifecycle: "optional runtime",
    description:
      "Cloudflare AI Gateway / Workers AI adapter helpers and docs bash tools.",
  },
  {
    importPath: "leadtype/lint",
    lifecycle: "build time",
    description: "Lint APIs and the `leadtype lint` CLI.",
  },
];

export type SmokeCoverage =
  | "agent docs"
  | "browser hydration"
  | "pipeline conversion"
  | "runtime render"
  | "search/API";

export const componentMatrix: Array<{
  coverage: SmokeCoverage[];
  name: string;
  note: string;
}> = [
  {
    name: "Callout",
    coverage: ["runtime render", "agent docs"],
    note: "App-owned semantic note blocks rendered from MDX.",
  },
  {
    name: "Card / Cards",
    coverage: ["runtime render", "agent docs"],
    note: "App-owned card grids rendered directly from authoring MDX.",
  },
  {
    name: "Steps / Step",
    coverage: ["runtime render", "agent docs"],
    note: "App-owned walkthrough content rendered as semantic ordered lists.",
  },
  {
    name: "Tabs / Tab",
    coverage: ["runtime render", "browser hydration", "agent docs"],
    note: "App-owned tab panels with keyboard navigation in the browser.",
  },
  {
    name: "CommandTabs",
    coverage: ["runtime render", "browser hydration", "agent docs"],
    note: "App-owned command switcher for install, run, or create commands.",
  },
  {
    name: "Prompt",
    coverage: ["runtime render", "browser hydration", "agent docs"],
    note: "Copyable agent prompts that flatten into explicit prompt blocks.",
  },
  {
    name: "Audience",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Human-only and agent-only guidance without duplicating pages.",
  },
  {
    name: "FileTree / Folder / File",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Project structure diagrams that flatten into readable text trees.",
  },
  {
    name: "Accordion / AccordionItem",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Collapsible details that still flatten into generated markdown.",
  },
  {
    name: "Example",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Data-driven preview and source examples for authored MDX.",
  },
  {
    name: "TopicSwitcher",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "Reader-facing navigation across equivalent docs topics.",
  },
  {
    name: "Selector",
    coverage: ["runtime render", "browser hydration"],
    note: "App-owned selector drives the guided recipe playground.",
  },
  {
    name: "Mermaid",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "App-owned code-block fallback that consumers can enhance later.",
  },
  {
    name: "TypeTable",
    coverage: ["runtime render", "pipeline conversion", "agent docs"],
    note: "App-owned prop tables rendered in-browser from MDX props.",
  },
  {
    name: "ExtractedTypeTable",
    coverage: ["runtime render", "pipeline conversion"],
    note: "App-owned rendering for type data still extracted by the pipeline.",
  },
  {
    name: "Search APIs",
    coverage: ["search/API", "browser hydration"],
    note: "Generated static index, server routes, and optional AI answer streaming.",
  },
];
